package com.wjapp.beans;
// Generated 2017-7-14 15:45:30 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "moviedb")
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private String name;
	private Date lastUpdate;
	//private Set<FilmCategory> filmCategories = new HashSet<FilmCategory>(0);
	
	private Set<Film> filmCategories = new HashSet<Film>(0);
	



	public Category() {
	}

	public Category(String name, Date lastUpdate) {
		this.name = name;
		this.lastUpdate = lastUpdate;
	}

	public Category(String name, Date lastUpdate, Set<Film> filmCategories) {
		this.name = name;
		this.lastUpdate = lastUpdate;
		this.filmCategories = filmCategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "name", nullable = false, length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", nullable = true, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	
	@ManyToMany(mappedBy = "filmCategories")
	public Set<Film> getFilmCategories() {
		return this.filmCategories;
	}

	public void setFilmCategories(Set<Film> filmCategories) {
		this.filmCategories = filmCategories;
	}

	


}
