package com.wjapp.beans;
// Generated 2017-7-14 15:45:30 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hall generated by hbm2java
 */
@Entity
@Table(name = "hall", catalog = "moviedb")
public class Hall implements java.io.Serializable {

	private Integer hallId;
	private Store store;
	private String name;
	private String type;
	private Integer steatcount;
	private Set<Schedule> schedules = new HashSet<Schedule>(0);

	public Hall() {
	}

	public Hall(Store store, String name, String type, Integer steatcount, Set<Schedule> schedules) {
		this.store = store;
		this.name = name;
		this.type = type;
		this.steatcount = steatcount;
		this.schedules = schedules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "hall_id", unique = true, nullable = false)
	public Integer getHallId() {
		return this.hallId;
	}

	public void setHallId(Integer hallId) {
		this.hallId = hallId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "steatcount")
	public Integer getSteatcount() {
		return this.steatcount;
	}

	public void setSteatcount(Integer steatcount) {
		this.steatcount = steatcount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hall")
	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

}
