package com.wjapp.beans;
// Generated 2017-7-14 15:45:30 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Seat generated by hbm2java
 */
@Entity
@Table(name = "seat", catalog = "moviedb")
public class Seat implements java.io.Serializable {

	private Integer seatId;
	private Schedule schedule;
	private Short row;
	private Short column;
	private String type;

	public Seat() {
	}

	public Seat(Schedule schedule, Short row, Short column, String type) {
		this.schedule = schedule;
		this.row = row;
		this.column = column;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "seat_id", unique = true, nullable = false)
	public Integer getSeatId() {
		return this.seatId;
	}

	public void setSeatId(Integer seatId) {
		this.seatId = seatId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schedule_id",nullable = true)
	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	@Column(name = "srow")
	public Short getRow() {
		return this.row;
	}

	public void setRow(Short row) {
		this.row = row;
	}

	@Column(name = "scolumn")
	public Short getColumn() {
		return this.column;
	}

	public void setColumn(Short column) {
		this.column = column;
	}

	@Column(name = "type", length = 8)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
